#!/usr/bin/env bash
# Bootstrap PingMe app on xprem: create app, download signing cert, API key, branch + channel.
# Usage (on VPS or against any xprem URL):
#   XPREM_URL=https://ota.pingme.hostyler.cloud \
#   XPREM_ADMIN_EMAIL=... XPREM_ADMIN_PASSWORD=... \
#   bash scripts/bootstrap-xprem.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CERT_OUT="${ROOT_DIR}/apps/mobile/certs/certificate.pem"
SECRETS_OUT="${ROOT_DIR}/infrastructure/ota/bootstrap.secrets.env"

: "${XPREM_URL:?Set XPREM_URL, e.g. https://ota.pingme.hostyler.cloud}"
: "${XPREM_ADMIN_EMAIL:?Set XPREM_ADMIN_EMAIL}"
: "${XPREM_ADMIN_PASSWORD:?Set XPREM_ADMIN_PASSWORD}"

CHANNEL="${XPREM_CHANNEL:-staging}"
BRANCH="${XPREM_BRANCH:-staging}"
APP_NAME="${XPREM_APP_NAME:-PingMe}"

login() {
  curl -fsS -X POST "${XPREM_URL}/auth/login" \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode "email=${XPREM_ADMIN_EMAIL}" \
    --data-urlencode "password=${XPREM_ADMIN_PASSWORD}" \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["token"])'
}

TOKEN="$(login)"
AUTH=(-H "Authorization: Bearer ${TOKEN}")

echo "Checking xprem health..."
curl -fsS "${XPREM_URL}/hc" >/dev/null

EXISTING_APP_ID="$(curl -fsS "${AUTH[@]}" "${XPREM_URL}/api/apps" | python3 -c '
import sys, json
apps = json.load(sys.stdin)
for app in apps:
    if app.get("name") == "'"${APP_NAME}"'":
        print(app["id"])
        break
')"

if [[ -n "${EXISTING_APP_ID}" ]]; then
  APP_ID="${EXISTING_APP_ID}"
  echo "Reusing existing app: ${APP_ID}"
else
  echo "Creating app ${APP_NAME}..."
  APP_ID="$(curl -fsS -X POST "${AUTH[@]}" "${XPREM_URL}/api/apps" \
    -H 'Content-Type: application/json' \
    -d '{"name":"'"${APP_NAME}"'","keysConfig":{"mode":"database"}}' \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["appId"])')"
  echo "Created app: ${APP_ID}"
fi

mkdir -p "$(dirname "${CERT_OUT}")"
echo "Downloading signing certificate..."
curl -fsS "${AUTH[@]}" "${XPREM_URL}/api/apps/${APP_ID}/certificate" -o "${CERT_OUT}"

BRANCH_EXISTS="$(curl -fsS "${AUTH[@]}" "${XPREM_URL}/api/apps/${APP_ID}/branches" | python3 -c '
import sys, json
branches = json.load(sys.stdin)
print("yes" if any(b.get("branchName") == "'"${BRANCH}"'" for b in branches) else "no")
' 2>/dev/null || echo no)"

if [[ "${BRANCH_EXISTS}" != "yes" ]]; then
  echo "Creating branch ${BRANCH}..."
  curl -fsS -X POST "${AUTH[@]}" "${XPREM_URL}/api/apps/${APP_ID}/branches" \
    -H 'Content-Type: application/json' \
    -d '{"branchName":"'"${BRANCH}"'"}' >/dev/null
fi

CHANNEL_EXISTS="$(curl -fsS "${AUTH[@]}" "${XPREM_URL}/api/apps/${APP_ID}/channels" | python3 -c '
import sys, json
channels = json.load(sys.stdin)
print("yes" if any(
    c.get("releaseChannelName") == "'"${CHANNEL}"'"
    or c.get("channelName") == "'"${CHANNEL}"'"
    or c.get("name") == "'"${CHANNEL}"'"
    for c in channels
) else "no")
' 2>/dev/null || echo no)"

if [[ "${CHANNEL_EXISTS}" != "yes" ]]; then
  echo "Creating channel ${CHANNEL} -> ${BRANCH}..."
  curl -fsS -X POST "${AUTH[@]}" "${XPREM_URL}/api/apps/${APP_ID}/channels" \
    -H 'Content-Type: application/json' \
    -d '{"channelName":"'"${CHANNEL}"'","branchName":"'"${BRANCH}"'"}' >/dev/null
fi

API_KEY=""
if [[ -f "${SECRETS_OUT}" ]]; then
  # shellcheck disable=SC1090
  source "${SECRETS_OUT}"
  if [[ "${EXPO_OTA_APP_ID:-}" == "${APP_ID}" && -n "${EOO_TOKEN:-}" ]]; then
    API_KEY="${EOO_TOKEN}"
    echo "Reusing API key from ${SECRETS_OUT}"
  fi
fi

if [[ -z "${API_KEY}" ]]; then
  echo "Creating publish API key..."
  API_KEY="$(curl -fsS -X POST "${AUTH[@]}" "${XPREM_URL}/api/apps/${APP_ID}/apiKeys" \
    -H 'Content-Type: application/json' \
    -d '{"name":"publish-cli"}' \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["apiKey"])')"
fi

mkdir -p "$(dirname "${SECRETS_OUT}")"
cat > "${SECRETS_OUT}" <<EOF
# Generated by scripts/bootstrap-xprem.sh — keep private (gitignored).
EXPO_OTA_APP_ID=${APP_ID}
EXPO_OTA_CHANNEL=${CHANNEL}
EXPO_OTA_BRANCH=${BRANCH}
EOO_TOKEN=${API_KEY}
XPREM_URL=${XPREM_URL}
EOF
chmod 600 "${SECRETS_OUT}"

echo ""
echo "Bootstrap complete."
echo "  App ID:     ${APP_ID}"
echo "  Channel:    ${CHANNEL}"
echo "  Branch:     ${BRANCH}"
echo "  Cert:       ${CERT_OUT}"
echo "  Secrets:    ${SECRETS_OUT}"
echo ""
echo "Next:"
echo "  source ${SECRETS_OUT}"
echo "  cd apps/mobile && npx expo prebuild && cd android && ./gradlew assembleRelease"
